CREATE TABLE "Retro" (
    retroId TEXT NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    userId TEXT NOT NULL,
    CONSTRAINT "Retro_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "RetroCard" (
    retroCardId TEXT NOT NULL PRIMARY KEY,
    body TEXT NOT NULL,
    createDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateDate DATETIME NOT NULL,
    retroColumnID TEXT NOT NULL,
    retroId TEXT NOT NULL,
    CONSTRAINT "RetroCard_RetroId_fkey" FOREIGN KEY (RetroId) REFERENCES "Retro" ("RetroId") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "RetroColumn" (
    retroColumnId TEXT NOT NULL PRIMARY KEY,
    body TEXT NOT NULL,
    createDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateDate DATETIME NOT NULL,
    retroId TEXT NOT NULL,
    CONSTRAINT "RetroCard_RetroId_fkey" FOREIGN KEY (RetroId) REFERENCES "Retro" ("RetroId") ON DELETE CASCADE ON UPDATE CASCADE
);


